# Site settings
title: This Developers Drive
email: william.pegg.dev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/startbootstrap-clean-blog-jekyll" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: wpegg3
github_username:  wpegg-dev

# Build settings
highlighter: true
markdown: kramdown
permalink: pretty
